//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixProLoudnessMatch.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FenixProLoudnessMatch.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string analyzeOriginal {
            get {
                return ResourceManager.GetString("analyzeOriginal", resourceCulture);
            }
        }
        
        public static string analyzeReplacement {
            get {
                return ResourceManager.GetString("analyzeReplacement", resourceCulture);
            }
        }
        
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        public static string origFilesLabel {
            get {
                return ResourceManager.GetString("origFilesLabel", resourceCulture);
            }
        }
        
        public static string origFilesTooltip {
            get {
                return ResourceManager.GetString("origFilesTooltip", resourceCulture);
            }
        }
        
        public static string replFilesLabel {
            get {
                return ResourceManager.GetString("replFilesLabel", resourceCulture);
            }
        }
        
        public static string replFilesTooltip {
            get {
                return ResourceManager.GetString("replFilesTooltip", resourceCulture);
            }
        }
        
        public static string outputFilesLabel {
            get {
                return ResourceManager.GetString("outputFilesLabel", resourceCulture);
            }
        }
        
        public static string outputFilesTooltip {
            get {
                return ResourceManager.GetString("outputFilesTooltip", resourceCulture);
            }
        }
        
        public static string showDiff {
            get {
                return ResourceManager.GetString("showDiff", resourceCulture);
            }
        }
        
        public static string matchLoudness {
            get {
                return ResourceManager.GetString("matchLoudness", resourceCulture);
            }
        }
        
        public static string progressIdle {
            get {
                return ResourceManager.GetString("progressIdle", resourceCulture);
            }
        }
        
        public static string msgErrorTitle {
            get {
                return ResourceManager.GetString("msgErrorTitle", resourceCulture);
            }
        }
        
        public static string msgErrorFmt {
            get {
                return ResourceManager.GetString("msgErrorFmt", resourceCulture);
            }
        }
        
        public static string origFolderDialogPickup {
            get {
                return ResourceManager.GetString("origFolderDialogPickup", resourceCulture);
            }
        }
        
        public static string replFolderDialogPickup {
            get {
                return ResourceManager.GetString("replFolderDialogPickup", resourceCulture);
            }
        }
        
        public static string outputFolderDialogPickup {
            get {
                return ResourceManager.GetString("outputFolderDialogPickup", resourceCulture);
            }
        }
        
        public static string tglMatchBitrate {
            get {
                return ResourceManager.GetString("tglMatchBitrate", resourceCulture);
            }
        }
        
        public static string lblMatchBitrate {
            get {
                return ResourceManager.GetString("lblMatchBitrate", resourceCulture);
            }
        }
        
        public static string tglMatchChannels {
            get {
                return ResourceManager.GetString("tglMatchChannels", resourceCulture);
            }
        }
        
        public static string lblMatchChannels {
            get {
                return ResourceManager.GetString("lblMatchChannels", resourceCulture);
            }
        }
    }
}
