//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenixProLoudnessMatch.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FenixProLoudnessMatch.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Original.
        /// </summary>
        public static string analyzeOriginal {
            get {
                return ResourceManager.GetString("analyzeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Replacement.
        /// </summary>
        public static string analyzeReplacement {
            get {
                return ResourceManager.GetString("analyzeReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Loudness.
        /// </summary>
        public static string matchLoudness {
            get {
                return ResourceManager.GetString("matchLoudness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string msgErrorFmt {
            get {
                return ResourceManager.GetString("msgErrorFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Bad Happened!.
        /// </summary>
        public static string msgErrorTitle {
            get {
                return ResourceManager.GetString("msgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Files Folder.
        /// </summary>
        public static string origFilesLabel {
            get {
                return ResourceManager.GetString("origFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder with original sound files..
        /// </summary>
        public static string origFilesTooltip {
            get {
                return ResourceManager.GetString("origFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Original Folder:.
        /// </summary>
        public static string origFolderDialogPickup {
            get {
                return ResourceManager.GetString("origFolderDialogPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Destination Folder.
        /// </summary>
        public static string outputFilesLabel {
            get {
                return ResourceManager.GetString("outputFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder for files with matched loudness to Original..
        /// </summary>
        public static string outputFilesTooltip {
            get {
                return ResourceManager.GetString("outputFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder:.
        /// </summary>
        public static string outputFolderDialogPickup {
            get {
                return ResourceManager.GetString("outputFolderDialogPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string progressIdle {
            get {
                return ResourceManager.GetString("progressIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Files Folder.
        /// </summary>
        public static string replFilesLabel {
            get {
                return ResourceManager.GetString("replFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder with replacement sound files..
        /// </summary>
        public static string replFilesTooltip {
            get {
                return ResourceManager.GetString("replFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Replacement Folder:.
        /// </summary>
        public static string replFolderDialogPickup {
            get {
                return ResourceManager.GetString("replFolderDialogPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Diff.
        /// </summary>
        public static string showDiff {
            get {
                return ResourceManager.GetString("showDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
